### PR TITLE
Add Project Showcase

### PR DESCRIPTION
**Pull request by Chris-Johnston**
Adds a project showcase. Incomplete. Lists projects by the award category, then in alphabetical order.

- [x] fill in description for all projects
- [ ] request screenshots / more description for all award winners if they have not provided them
- [x] fill in github links
- [x] fill in demo site links
- [x] add CROBBER
- [x] add link to the showcase visible from the homepage, maybe just duplicate the docs link and have it on the top
- [x] change RSVP button to go to the showcase?
- [x] add link to the repo if people want to amend their descriptions so they can just PR it

@UWB-ACM/hackathon-content-team could use your help on this, just _oooone_ last thing

### CODE REVIEW

**Comment by etcadinfinitum** [comment]
Lmao are we actually gonna add crobber in there? I'm not opposed but just cracking up

Is there a model for this from last year? Would be down to help with this tomorrow if time allows

**Comment by Chris-Johnston** [comment]
> Is there a model for this from last year?
[Here's last year's student showcase.](https://uwb-acm.github.io/Hackathon-Docs-2018/Student-Projects.html) This is a huge improvement, mainly because we got down the information for all the projects this year.

As for the format of how things need to be structured, I think what I've filled in for now is fine. Going through the submission form and ensuring screenshots are all sensibly sized is just boring.

**Comment by Chris-Johnston** [comment]
image

btw here's what it looks like right now

**Comment by Chris-Johnston** [comment]
Ready for review. I was going to reach out to some teams which did not provide a full description of their project, but instead I think it's best we post this now and ask for them to update things later (doing so would take more time than I have patience at the moment).

**Pull request merged**
